#easy_admin:
imports:
    - {resource: admin/}
     
    
    
    
    
    
    
    
    #entities:
        # List the entity class name you want to manage
        #- App\Entity\Offre
        #- App\Entity\Categorie
        #- App\Entity\User
        #- App\Entity\Recruteur
