easy_admin:
  design: 
    form_theme:
          #- 'admin/form/custom_layout.html.twig'
          - 'form_div_layout.html.twig'
          - '@EasyAdmin/form/bootstrap_4.html.twig'
        brand_color: '#67b0d1' #1ABC9
        assets:
          favicon: 
            path: 'Squadfree/assets/img/favicon_perso.png'
    menu:
      - label: 'E-RECRUTEMENT'
        icon: 'newspaper-o'
        children:
          - {entity: 'Recruteur', icon: 'newspaper-o', label: 'Entreprise'}
          - {entity: 'User', icon: 'inbox', label: 'Candidat'}
          - {entity: 'Offre', icon: 'inbox', label: 'Offres'}
          - {entity: 'Categorie', icon: 'inbox', label: 'Categories'}
    