easy_admin:
  design: 
    form_theme:
          #- 'admin/form/custom_layout.html.twig'
      - 'form_div_layout.html.twig'
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      #- '@VichUploader/Form/fields.html.twig'
    brand_color: '#67b0d1' 
    assets:
      favicon: 
        path: 'Squadfree/assets/img/favicon_perso.png'
    menu:
      - label: 'E-RECRUTEMENT'
        icon: 'newspaper-o'
        children:
          - { label: 'Users' }
          - {entity: 'Recruteur', icon: 'user', label: 'Entreprise'}
          - {entity: 'User', icon: 'user', label: 'Candidat'} #, permission: 'ROLE_SUPER_ADMIN'
          - {entity: 'Administrateur', icon: 'user', label: 'Admin'}
          - { label: 'Offres' }
          - {entity: 'Offre', icon: 'tag', label: 'Offres'}
          - {entity: 'Categorie', icon: 'inbox', label: 'Categories'} 
          - {entity: 'Postuler', icon: 'user', label: 'Postulation'}
          - { label: 'Contact' }
          - {entity: 'Contact', icon: 'inbox', label: 'Contact'} 
          - { label: 'Accueil' } 
          - { label: 'Page accueil' , route: 'home'}
    