easy_admin:
  entities:
    Postuler:
      class: App\Entity\Postuler
      templates: #edition template
        edit: 'admin/edit.html.twig'
      list:
        #fields:
          #- {property: 'online', type: 'text'}
        actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}  