easy_admin:
  entities:
    Recruteur:
      class: App\Entity\Recruteur
      password_encoding: { algorithm: 'bcrypt', cost: 12 }
      form:
        fields:
          - {property: 'nom_entreprise'}
          - {property: 'secteur_activite'}
          - {property: 'adresse'}
          - {property: 'code_postal'}
          - {property: 'ville'}
          - {property: 'pays', type: 'country'}
                    #- {property: 'pays', type: 'App\Form\RecruteurType', mapped: false}
          - {property: 'description'}
          - {property: 'civility'}
          - {property: 'email', type: 'email'}
          - {property: 'password', type: 'password', params: { max: 15 }}
          #- {property: 'confirm_password'}
          - {property: 'offres'}
          - {property: 'phone', type: 'tel', icon: 'phone'}
      list:
        #fields:
          #- {property: 'online', type: 'text'}
        actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}    