easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - {property: 'nom'}
          - {property: 'prenom'}
          - {property: 'password', type: 'password', params: { max: 15 }}
          #- {property: 'confirm_password'}
          - {property: 'email'}
          - {property: 'username'}
          - {property: 'datenaissance', type_options: { widget: 'single_text' }}
          - {property: 'adresse'}
          - {property: 'nationalite', type: 'country'}
          - {property: 'postal_code'}
          - {property: 'civility'}
          - {property: 'level'}
          - {property: 'cvFile', type: 'vich_file'} #, base_path: 'livre/'
          - {property: 'avatarFile', type: 'vich_image'} #, base_path: 'images/'
          - {property: 'tel', type: 'tel'}
      list:
        #fields:
          #- {property: 'online', type: 'text'}
        actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}     